# Generated by Django 2.2.3 on 2019-07-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='one',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
